### ISSUE TITLE
小米，oppo手机退出后再登录报空，华为手机无问题

### ISSUE THREAD

**Issue by msheena** [markzhai/react-native-preloader#4]
React: Exception in native call from JS
                                                              java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.react.uimanager.ReactShadowNode.setStyleWidth(float)' on a null object reference
                                                                  at com.facebook.react.uimanager.UIImplementation.updateRootNodeSize(UIImplementation.java:136)
                                                                  at com.facebook.react.uimanager.UIManagerModule.updateRootNodeSize(UIManagerModule.java:195)
                                                                  at com.facebook.react.uimanager.UIManagerModule.access$000(UIManagerModule.java:62)
                                                                  at com.facebook.react.uimanager.UIManagerModule$1$1.run(UIManagerModule.java:178)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                  at java.lang.Thread.run(Thread.java:818)

**Comment by markzhai** [comment]
退出后再登录？？？？能不能说得清楚点

**Comment by mingkang1993** [comment]
@markzhai 第一次打开app（当前手机无此应用进程），然后按返回键退出应用（但进程并未杀死），再点开app，会出现两种情况，一是页面空白，无法加载出属于rn的那个页面；二是页面正常加载出来，但是再按返回键无反应，不能后退也不能退出。这两种情况在native里都报以上错误。目前发现小米和oppo的手机会出现这样的情况，请帮忙分析下，感谢~

**Comment by markzhai** [comment]
@mingkang1993 app里第一个activity就是rn的吗？是用了这个库？提供下rn版本号

**Comment by msheena** [comment]
@markzhai 第一个Activity是启动页，原生的，从启动页进入的登录注册页面是rn的,版本是0.31.0

**Comment by markzhai** [comment]
2个问题
1. 预加载是在启动页做的吗？启动页打开登录注册后，是否会finish
2. 返回键退出应用这边有改过默认行为吗？登录注册页面 destroy 了吗？下次进来是先到的哪个activity？

**Comment by msheena** [comment]
1.预加载是在启动页（原生）做的，打开登录注册（rn）后会finish
2.返回键退出应用没有更改过，登录注册页面destroy了，下次进来进的是启动页

**Comment by harveyhui** [comment]
请问问题解决了吗？
