### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.github.markzhai.react.preloader.demo/lib-main/libgnustl_shared.so" is 32-bit instead of 64-bit

### ISSUE THREAD

**Issue by ysq1051838264** [markzhai/react-native-preloader#6]
FATAL EXCEPTION: main
                                                                                          Process: com.github.markzhai.react.preloader.demo, PID: 15636
                                                                                          java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.github.markzhai.react.preloader.demo/lib-main/libgnustl_shared.so" is 32-bit instead of 64-bit
                                                                                              at java.lang.Runtime.load(Runtime.java:344)
                                                                                              at java.lang.System.load(System.java:1079)
                                                                                              at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:71)
                                                                                              at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
                                                                                              at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
                                                                                              at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:65)
                                                                                              at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
                                                                                              at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
                                                                                              at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:247)
                                                                                              at com.facebook.jni.Countable.<clinit>(Countable.java:22)
                                                                                              at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:39)
                                                                                              at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:22)
                                                                                              at com.facebook.react.JSCConfig$1.getConfigMap(JSCConfig.java:14)
                                                                                              at com.facebook.react.XReactInstanceManagerImpl.recreateReactContextInBackgroundFromBundleLoader(XReactInstanceManagerImpl.java:415)
                                                                                              at com.facebook.react.XReactInstanceManagerImpl.recreateReactContextInBackgroundInner(XReactInstanceManagerImpl.java:411)
                                                                                              at com.facebook.react.XReactInstanceManagerImpl.createReactContextInBackground(XReactInstanceManagerImpl.java:355)
                                                                                              at com.facebook.react.ReactRootView.startReactApplication(ReactRootView.java:215)
                                                                                              at com.github.markzhai.react.preloader.ReactPreLoader.init(ReactPreLoader.java:58)
                                                                                              at com.github.markzhai.react.preloader.demo.MainActivity.onCreate(MainActivity.java:32)
                                                                                              at android.app.Activity.performCreate(Activity.java:6367)
                                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
                                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2397)
                                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504)
                                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:165)
                                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                              at android.os.Looper.loop(Looper.java:150)
                                                                                              at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by ysq1051838264** [comment]
报这个错，求解
